# Generated by Django 2.2.6 on 2020-09-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('denorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dirtyinstance',
            unique_together={('content_type', 'object_id')},
        ),
    ]
